# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates

version: 2
updates:
- package-ecosystem: npm
  directory: /themes/conventional-branch/
  schedule:
    interval: monthly
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
